name: Run tests and deploy to GitHub pages if successful

on:
  push:
    branches:
      - main

jobs:
  run-unit-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b # v2.3.1

      - name: Setup Node 🔧
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: 16

      - name: Install and run unit tests 🔧
        run: | 
          npm install --force
          npm run test:unit

  deploy-gh-pages:
    needs: run-unit-tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b # v2.3.1

      - name: Apply local settings
        uses: finnp/create-file-action@ba7436058fbdd9579be2f36fcfb1b0ed1e692ab8 # master
        env:
          FILE_NAME: ".env.local"
          FILE_DATA: 'URL_PREFIX = "/crow/"'

      - name: Setup Node 🔧
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: 16

      - name: Install and build 🔧
        run: |
          npm install --force
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@049a95c516cd5723d8cfde79dc7a79fcdcbd6c97 # 4.0.0
        with:
          branch: gh-pages
          folder: docs